name          : VNet
in_channels   : 1
base_channels : 32
kernel_size   : [3, 3, 1]
depth         : 3
n_labels      : 4
n_dim         : 3
in_shape      : [64, 64, 10]
out_shape     : [64, 64, 10]
norm          : BatchNorm
block_type    : 2
attention     : False
