gpus: 0,1
epochs: 1000
validation_frequency: 4
early_stopping_epochs: 10
data: data_list.yaml

generator:
  train            :
    BlockSampler   :
      shuffle      : True
      block_shape  : [96, 96, 96]
      shift        : [16, 16, 16]
      # out_shape    : [96, 96, 20]
      n_workers    : 4
      n_samples    : 16
      ratios       : [0.3, 1, 1, 1]
      verbose      : False

    Augmentor      :
      # zoom_range   : [0.8, 1.2]
      # flip         : True
      # transpose    : False
      noise        : True
      window_width : 100
      window_level : 50
      n_workers    : 2
      verbose      : False

    BatchGenerator :
      batch_size   : 12
      n_workers    : 2
      verbose      : False

  valid            :
    BlockGenerator :
      block_shape  : [96, 96, 96]
      stride       : 48
      # out_shape    : [96, 96, 20]
      crop_shape   : [256, 256, -1]
      n_workers    : 4
      ordered      : True
      verbose      : False

    Augmentor      :
      window_width : 100
      window_level : 50
      n_workers    : 1
      verbose      : False

    BatchGenerator :
      batch_size   : 36
      n_workers    : 1
      verbose      : False

model: '../model.json5'
meter: '../meter.json5'

optimizer:
  name     : AdamW
  lr       : 0.001

scheduler:
  mode: max
  warmup: 10
  reduce_factor: 0.5
  patience: 50
