gpus: 0,1
epochs: 1000
validation_frequency: 2000
early_stopping_epochs: 15
data: data_list.yaml

generator:
  train            :
    BlockGenerator :
      block_shape  : [30, 30, 30]
      stride       : 15
      # out_shape    : [96, 96, 20]
      # crop_shape   : [256, 256, -1]
      n_workers    : 4
      ordered      : True
      verbose      : False
    # BlockSampler   :
    #   shuffle      : True
    #   block_shape  : [30, 30, 30]
    #   pad_first    : True
    #   # shift        : [20, 20, 20]
    #   # out_shape    : [20, 20, 20]
    #   n_workers    : 4
    #   n_samples    : 4
    #   ratios       : [1, 1, 1, 1]
    #   verbose      : False

    Augmentor      :                  # do preprocessing and data augmentation
      # zoom_range   : [0.8, 1.2]       # zoom the image/label with some scale in range, note that it only apply on x-y plane
      # flip         : True             # flip the image/only on x-y plane with a fixed probability 0.5
      # transpose    : False             # transpose the image/label on x-y plane with a fixed probability 0.5
      noise        : True             # add a Gaussian noise with mean 0 and sigam 0.05 on the image
      window_width : 400        # adjust the contrast with the given window width(or a range), default : 100
      window_level : 0         # adjust the contrast with the given window level(or a range), default : 50
      n_workers    : 2                # number of multi-thread workers
      verbose      : False            # toggle the debug info of this generator

    BatchGenerator :
      batch_size   : 128
      n_workers    : 2
      verbose      : False

  valid            :
    BlockGenerator :
      block_shape  : [30, 30, 30]
      stride       : 15
      # out_shape    : [96, 96, 20]
      # crop_shape   : [256, 256, -1]
      n_workers    : 4
      ordered      : True
      verbose      : False

    Augmentor      :                  # do preprocessing and data augmentation
      window_width : 400              # adjust the contrast with the given window width(or a range), default : 100
      window_level : 0               # adjust the contrast with the given window level(or a range), default : 50
      n_workers    : 1                # number of multi-thread workers
      verbose      : False            # toggle the debug info of this generator

    BatchGenerator :
      batch_size   : 4
      n_workers    : 1
      verbose      : False

optimizer:
  name     : Adam
  lr       : 0.001

scheduler:
  mode: max
  warmup: 10
  reduce_factor: 0.5
  patience: 50

early_stopper:
  mode: max
  patience: 10
