gpus: 1
epochs: 500
validation_frequency: 5
early_stopping_epochs: 10
output_threshold: 0.2
data: ../data_list.yaml

generator:
  train            :
    BlockSampler   :
      shuffle      : True
      block_shape  : [128, 128, 30]
      out_shape    : [96, 96, 20]
      n_workers    : 4
      n_samples    : 32
      # target_ratio : [0.1, 0.35, 0.35]
      verbose      : False

    # Augmentor      :
    #   zoom_range   : [0.5, 1.2]
    #   filter_range : [0.9, 1.0]
    #   transpose    : False
    #   flip         : False
    #   n_workers    : 2
    #   verbose      : False

    BatchGenerator :
      batch_size   : 32
      n_workers    : 4
      verbose      : False

  valid            :
    BlockGenerator :
      block_shape  : [128, 128, 30]
      out_shape    : [96, 96, 20]
      n_workers    : 4
      ordered      : True
      verbose      : False

    BatchGenerator :
      n_workers    : 1
      batch_size   : 120
      verbose      : False

model:
  name          : VNet
  in_channels   : 1
  base_channels : 16
  kernel_size   : 5
  depth         : 4
  n_labels      : 2
  n_dim         : 3
  in_shape      : [128, 128, 30]
  out_shape     : [96, 96, 20]
  norm          : BatchNorm
  block_type    : 2
  attention     : False

loss:
  name: dice_loss
  weight: [0, 1]

optimizer:
  name     : Adam
  lr       : 0.001

scheduler:
  T_mult   : 1
  T_up     : 10
